/**
 * The canopy voxel update pass — WP 3.1's storage stepped by WP 3.2's kinetics, driven by
 * WP 3.3's irradiance and WP 3.4's plume.
 *
 * Four packages shipped complete and none of them owned this join, which is why M3 was
 * "delivered and not composed" for as long as it was. WP 3.4's shader header says it outright:
 * *"whoever wires this into WP 3.1's voxel pass must profile it"*. There was no such pass.
 *
 * The dispatch is over ALLOCATED SLOTS, not dense voxels: 1.2 M against 16.8 M on the measured
 * worst-case world, so the sparsity WP 3.1 bought is spent here and nowhere else.
 *
 * Not re-exported from a barrel — it imports WGSL and touches `GPUDevice`, and everything in
 * `@sim/canopy/*` has to stay importable from a Vitest run under Node.
 */

import CONVECTION_WGSL from '../../../shaders/sim/canopy/convection/convection.wgsl?raw'
import VOXEL_STEP_WGSL from '../../../shaders/sim/canopy/voxel_step.wgsl?raw'
import { canopyStorageWgsl } from './storage/shaders.ts'
import { radiationPrelude, type RadiationShaderOptions, DEFAULT_SHADER_OPTIONS } from './radiation/shaders.ts'
import type { CanopyLayout } from './storage/layout.ts'
import { Z_MASK, ZCOUNT_SHIFT } from './storage/layout.ts'
import {
  BOUND_WATER_DESORPTION_HEAT,
  CHAR_SPECIFIC_HEAT,
  CHAR_YIELD,
  CRITICAL_MASS_FLUX,
  PYROLYSIS_A,
  PYROLYSIS_E_OVER_R,
  PYROLYSIS_HEAT,
  SOLID_CONDUCTIVITY,
  SOLID_SPECIFIC_HEAT,
  STEFAN_BOLTZMANN,
  WATER_BOILING_K,
  WATER_LATENT_HEAT,
  WATER_SPECIFIC_HEAT,
} from './kinetics/constants.ts'

/** Bind group each subsystem occupies. `convection.wgsl` hard-codes group 3; the rest follow. */
export const VOXEL_GROUP_PARAMS = 0
export const VOXEL_GROUP_STORAGE = 1
export const VOXEL_GROUP_IRRADIANCE = 2
export const VOXEL_GROUP_PLUME = 3

/**
 * Fraction of the initial load below which an ignited voxel is called char, and the fraction
 * of the ignition gate at which it is called pyrolysing.
 *
 * Both are private to `kinetics/voxel.ts` — the classification thresholds, not physics — so
 * they are restated here rather than exported from there and given a second owner. The mirror
 * test pins them together.
 */
export const PYROLYSING_FRACTION = 0.01
export const CHAR_FRACTION = 0.05

/**
 * Foliage particle diameter, m. A 1 mm needle at h = 154 gives Bi = 0.19 (spec §7.6), which is
 * the marginal regime the lumped model plus the Biot correction is built for.
 *
 * ponytail: one diameter for the whole canopy. The store carries a per-voxel SAV code, so this
 * becomes `4/SAV` per voxel the moment anything needs it to.
 */
export const DEFAULT_PARTICLE_DIAMETER_M = 0.001

const f = (v: number): string => (Number.isInteger(v) ? `${v}.0` : `${v}`)

/** Every kinetics constant the shader uses, emitted from the TypeScript that defines it. */
export function kineticsPrelude(): string {
  return `// GENERATED by src/sim/canopy/voxelStep.ts — the oracle is kinetics/constants.ts
const STEFAN_BOLTZMANN: f32 = ${f(STEFAN_BOLTZMANN)};
const WATER_LATENT_HEAT: f32 = ${f(WATER_LATENT_HEAT)};
const WATER_BOILING_K: f32 = ${f(WATER_BOILING_K)};
const WATER_SPECIFIC_HEAT: f32 = ${f(WATER_SPECIFIC_HEAT)};
const BOUND_WATER_DESORPTION_HEAT: f32 = ${f(BOUND_WATER_DESORPTION_HEAT)};
const SOLID_SPECIFIC_HEAT: f32 = ${f(SOLID_SPECIFIC_HEAT)};
const CHAR_SPECIFIC_HEAT: f32 = ${f(CHAR_SPECIFIC_HEAT)};
const SOLID_CONDUCTIVITY: f32 = ${f(SOLID_CONDUCTIVITY)};
const PYROLYSIS_HEAT: f32 = ${f(PYROLYSIS_HEAT)};
const CHAR_YIELD: f32 = ${f(CHAR_YIELD)};
const PYROLYSIS_A: f32 = ${f(PYROLYSIS_A)};
const PYROLYSIS_E_OVER_R: f32 = ${f(PYROLYSIS_E_OVER_R)};
const CRITICAL_MASS_FLUX: f32 = ${f(CRITICAL_MASS_FLUX)};
const PYROLYSING_FRACTION: f32 = ${f(PYROLYSING_FRACTION)};
const CHAR_FRACTION: f32 = ${f(CHAR_FRACTION)};
`
}

/** The complete module: storage addressing, radiation constants, convection, kinetics, pass. */
export function buildVoxelStepShader(
  opts: RadiationShaderOptions = DEFAULT_SHADER_OPTIONS,
): string {
  return [
    canopyStorageWgsl(VOXEL_GROUP_STORAGE),
    radiationPrelude(opts),
    kineticsPrelude(),
    CONVECTION_WGSL,
    VOXEL_STEP_WGSL,
  ].join('\n')
}

/**
 * Column index of every allocated slot.
 *
 * The layout maps (column, k) → slot; the pass needs the inverse to recover a slot's world
 * position, and a search per invocation would be absurd for a value that never changes. One
 * u32 per slot — 4.8 MiB on the worst measured world, against the 38 MiB the pools already
 * cost.
 *
 * Pure, so it is tested on the CLI. An off-by-one here puts every voxel's heating in the wrong
 * column and nothing reports an error.
 */
export function buildSlotMap(layout: CanopyLayout): Uint32Array<ArrayBuffer> {
  const out = new Uint32Array(layout.voxelCount)
  const columns = layout.columnHeader.length
  for (let c = 0; c < columns; c++) {
    const header = layout.columnHeader[c] as number
    const count = (header >>> ZCOUNT_SHIFT) & Z_MASK
    if (count === 0) continue
    const offset = layout.columnOffset[c] as number
    for (let d = 0; d < count; d++) out[offset + d] = c
  }
  return out
}

export interface VoxelStepOptions {
  readonly ambientK?: number
  readonly particleDiameter?: number
  readonly shader?: RadiationShaderOptions
}

export interface VoxelStepResources {
  /** WP 3.1's store, as five buffers in the order `canopyStoragePrelude` declares them. */
  readonly columns: GPUBuffer
  readonly ground: GPUBuffer
  readonly poolA: GPUBuffer
  readonly poolB: GPUBuffer
  readonly poolC: GPUBuffer
  /** WP 3.3's irradiance field, kW/m². */
  readonly irradiance: GPUTexture
  /** WP 3.4's packed plume uniforms. */
  readonly plume: GPUBuffer
}

const PARAMS_BYTES = 16
const STAT_SLOTS = 2
const WORKGROUP = 64

export class CanopyVoxelStep {
  /** `[flaming, everIgnited]`. The acceptance number for crown fire actually happening. */
  readonly stats: GPUBuffer

  readonly slotCount: number

  private readonly device: GPUDevice
  private readonly params: GPUBuffer
  private readonly slotMap: GPUBuffer
  private readonly stepPipeline: GPUComputePipeline
  private readonly clearPipeline: GPUComputePipeline
  private readonly paramsGroup: GPUBindGroup
  private readonly clearGroup: GPUBindGroup
  private readonly storageGroup: GPUBindGroup
  private readonly irradianceGroup: GPUBindGroup
  private readonly plumeGroup: GPUBindGroup
  private readonly ambientK: number
  private readonly particleDiameter: number
  private readonly sampler: GPUSampler

  constructor(
    device: GPUDevice,
    layout: CanopyLayout,
    resources: VoxelStepResources,
    options: VoxelStepOptions = {},
  ) {
    this.device = device
    this.slotCount = layout.voxelCount
    this.ambientK = options.ambientK ?? 293.15
    this.particleDiameter = options.particleDiameter ?? DEFAULT_PARTICLE_DIAMETER_M

    const map = buildSlotMap(layout)
    this.slotMap = device.createBuffer({
      label: 'canopy.slotColumn',
      size: Math.max(4, map.byteLength),
      usage: GPUBufferUsage.STORAGE | GPUBufferUsage.COPY_DST,
    })
    if (map.length > 0) device.queue.writeBuffer(this.slotMap, 0, map)

    this.params = device.createBuffer({
      label: 'canopy.voxelStepParams',
      size: PARAMS_BYTES,
      usage: GPUBufferUsage.UNIFORM | GPUBufferUsage.COPY_DST,
    })
    this.stats = device.createBuffer({
      label: 'canopy.voxelStats',
      size: STAT_SLOTS * 4,
      usage: GPUBufferUsage.STORAGE | GPUBufferUsage.COPY_SRC,
    })
    this.sampler = device.createSampler({
      label: 'canopy.irradianceSampler',
      magFilter: 'linear',
      minFilter: 'linear',
      addressModeU: 'clamp-to-edge',
      addressModeV: 'clamp-to-edge',
      addressModeW: 'clamp-to-edge',
    })

    const module = device.createShaderModule({
      label: 'canopy.voxelStep',
      code: buildVoxelStepShader(options.shader ?? DEFAULT_SHADER_OPTIONS),
    })
    const make = (entryPoint: string): GPUComputePipeline =>
      device.createComputePipeline({
        label: `canopy.voxelStep.${entryPoint}`,
        layout: 'auto',
        compute: { module, entryPoint },
      })
    this.stepPipeline = make('step')
    this.clearPipeline = make('clearStats')

    this.paramsGroup = device.createBindGroup({
      label: 'canopy.voxelStep.params',
      layout: this.stepPipeline.getBindGroupLayout(VOXEL_GROUP_PARAMS),
      entries: [
        { binding: 0, resource: { buffer: this.params } },
        { binding: 1, resource: { buffer: this.slotMap } },
        { binding: 2, resource: { buffer: this.stats } },
      ],
    })
    // `clearStats` touches only the counters, so `layout: 'auto'` gives it a group with that
    // one binding and the full params group is incompatible with it.
    this.clearGroup = device.createBindGroup({
      label: 'canopy.voxelStep.clearStats',
      layout: this.clearPipeline.getBindGroupLayout(0),
      entries: [{ binding: 2, resource: { buffer: this.stats } }],
    })
    this.storageGroup = device.createBindGroup({
      label: 'canopy.voxelStep.storage',
      layout: this.stepPipeline.getBindGroupLayout(VOXEL_GROUP_STORAGE),
      entries: [
        { binding: 0, resource: { buffer: resources.columns } },
        { binding: 1, resource: { buffer: resources.ground } },
        { binding: 2, resource: { buffer: resources.poolA } },
        { binding: 3, resource: { buffer: resources.poolB } },
        { binding: 4, resource: { buffer: resources.poolC } },
      ],
    })
    this.irradianceGroup = device.createBindGroup({
      label: 'canopy.voxelStep.irradiance',
      layout: this.stepPipeline.getBindGroupLayout(VOXEL_GROUP_IRRADIANCE),
      entries: [
        { binding: 0, resource: resources.irradiance.createView() },
        { binding: 1, resource: this.sampler },
      ],
    })
    this.plumeGroup = device.createBindGroup({
      label: 'canopy.voxelStep.plume',
      layout: this.stepPipeline.getBindGroupLayout(VOXEL_GROUP_PLUME),
      entries: [{ binding: 0, resource: { buffer: resources.plume } }],
    })
  }

  /**
   * One canopy step.
   *
   * Runs at the canopy step rate, NOT at the radiation rate: convection ignites fuel in about
   * a second (spec §7.5) and is the fast channel. Only the irradiance FIELD is amortised.
   */
  encode(encoder: GPUCommandEncoder, dtSeconds: number): void {
    if (this.slotCount === 0 || !(dtSeconds > 0)) return
    this.writeParams(dtSeconds)

    const clear = encoder.beginComputePass({ label: 'canopy.voxelStep.clearStats' })
    clear.setPipeline(this.clearPipeline)
    clear.setBindGroup(0, this.clearGroup)
    clear.dispatchWorkgroups(1)
    clear.end()

    const pass = encoder.beginComputePass({ label: 'canopy.voxelStep' })
    pass.setPipeline(this.stepPipeline)
    pass.setBindGroup(VOXEL_GROUP_PARAMS, this.paramsGroup)
    pass.setBindGroup(VOXEL_GROUP_STORAGE, this.storageGroup)
    pass.setBindGroup(VOXEL_GROUP_IRRADIANCE, this.irradianceGroup)
    pass.setBindGroup(VOXEL_GROUP_PLUME, this.plumeGroup)
    pass.dispatchWorkgroups(Math.ceil(this.slotCount / WORKGROUP))
    pass.end()
  }

  destroy(): void {
    this.params.destroy()
    this.slotMap.destroy()
    this.stats.destroy()
  }

  private writeParams(dt: number): void {
    const buf = new ArrayBuffer(PARAMS_BYTES)
    const v = new DataView(buf)
    v.setFloat32(0, dt, true)
    v.setUint32(4, this.slotCount, true)
    v.setFloat32(8, this.ambientK, true)
    v.setFloat32(12, this.particleDiameter, true)
    this.device.queue.writeBuffer(this.params, 0, buf)
  }
}
