/**
 * The WGSL constant prelude, generated from the TypeScript constants.
 *
 * Every number that both sides must agree on — workgroup sizes, bucket limits, bit packing,
 * stats slot indices — is emitted here and consumed by the shaders as a named constant. That
 * makes drift structurally impossible rather than merely tested for: there is no second copy
 * to fall out of date.
 *
 * The prelude is prepended to every module in the package, so the same names mean the same
 * thing in the cull, scan, scatter, tree-draw and grass shaders.
 */

import {
  CULL_WORKGROUP_SIZE,
  GRASS_CULL_WORKGROUP_SIZE,
  GRASS_VERTS_PER_BLADE,
  LOD_COUNT,
  MAX_BUCKETS,
  SCAN_WORKGROUP_SIZE,
} from './config.ts'
import {
  COMPACTED_FADE_MAX,
  COMPACTED_INDEX_BITS,
  CONTROL_HEADER_U32S,
  CONTROL_OFF_RECORD_COUNT,
  MATERIAL_FLAG_ALPHA_TEST,
  MATERIAL_FLAG_BURNABLE,
  MATERIAL_FLAG_DOUBLE_SIDED,
  STATS_CLAMP_EVENTS,
  STATS_GRASS_BLADES,
  STATS_GRASS_TILES,
  STATS_RECORDS_APPENDED,
  STATS_TREES_CULLED,
  STATS_TREES_VISIBLE,
  STATS_TRIANGLES,
} from './layout.ts'
import { MAX_WIDTH_COMPENSATION } from './grassMath.ts'
import { DOMAIN_SIZE_M } from '@contracts/world'
import { BURN_LAYER_COUNT } from '@render/materials/patterns.ts'
import { BURN_CROWN_SCALE, BURN_PEAK_SCALE } from './layout.ts'

/** Emit a WGSL `u32` literal. */
const u = (v: number): string => `${Math.trunc(v)}u`
/** Emit a WGSL `f32` literal that always carries a decimal point. */
const f = (v: number): string => (Number.isInteger(v) ? `${v}.0` : `${v}`)

export interface PreludeOptions {
  /** Enables the `subgroups` code path in the scan. */
  readonly useSubgroups: boolean
  /** `dither` discards against a screen-space hash; `alpha-to-coverage` needs MSAA. */
  readonly ditherAlpha: boolean
}

export function foliagePrelude(opts: PreludeOptions): string {
  return `// GENERATED by src/render/foliage/shaderPrelude.ts — do not edit in the .wgsl files.
const CULL_WG: u32 = ${u(CULL_WORKGROUP_SIZE)};
const SCAN_WG: u32 = ${u(SCAN_WORKGROUP_SIZE)};
const GRASS_WG: u32 = ${u(GRASS_CULL_WORKGROUP_SIZE)};
const MAX_BUCKETS: u32 = ${u(MAX_BUCKETS)};
const BUCKETS_PER_SCAN_THREAD: u32 = ${u(MAX_BUCKETS / SCAN_WORKGROUP_SIZE)};
const LOD_COUNT: u32 = ${u(LOD_COUNT)};
const VERTS_PER_BLADE: u32 = ${u(GRASS_VERTS_PER_BLADE)};
const DOMAIN_SIZE_M: f32 = ${f(DOMAIN_SIZE_M)};

const COMPACTED_INDEX_BITS: u32 = ${u(COMPACTED_INDEX_BITS)};
const COMPACTED_INDEX_MASK: u32 = ${u((1 << COMPACTED_INDEX_BITS) - 1)};
const COMPACTED_FADE_MAX: f32 = ${f(COMPACTED_FADE_MAX)};

const STATS_TREES_VISIBLE: u32 = ${u(STATS_TREES_VISIBLE)};
const STATS_TREES_CULLED: u32 = ${u(STATS_TREES_CULLED)};
const STATS_RECORDS_APPENDED: u32 = ${u(STATS_RECORDS_APPENDED)};
const STATS_TRIANGLES: u32 = ${u(STATS_TRIANGLES)};
const STATS_GRASS_BLADES: u32 = ${u(STATS_GRASS_BLADES)};
const STATS_GRASS_TILES: u32 = ${u(STATS_GRASS_TILES)};
const STATS_CLAMP_EVENTS: u32 = ${u(STATS_CLAMP_EVENTS)};
const CONTROL_OFF_RECORD_COUNT: u32 = ${u(CONTROL_OFF_RECORD_COUNT)};
const CONTROL_HEADER_U32S: u32 = ${u(CONTROL_HEADER_U32S)};

const MATERIAL_FLAG_ALPHA_TEST: u32 = ${u(MATERIAL_FLAG_ALPHA_TEST)};
const MATERIAL_FLAG_DOUBLE_SIDED: u32 = ${u(MATERIAL_FLAG_DOUBLE_SIDED)};
const MATERIAL_FLAG_BURNABLE: u32 = ${u(MATERIAL_FLAG_BURNABLE)};
const MAX_WIDTH_COMPENSATION: f32 = ${f(MAX_WIDTH_COMPENSATION)};
const BURN_LAYER_COUNT: u32 = ${u(BURN_LAYER_COUNT)};
const BURN_PEAK_SCALE: f32 = ${f(BURN_PEAK_SCALE)};
const BURN_CROWN_SCALE: f32 = ${f(BURN_CROWN_SCALE)};
// Bark stops at the char stage; only foliage runs on to ash. One stage short of the end, in
// the same 0..1 coordinate burnLayers divides by BURN_LAYER_COUNT - 1.
const BARK_MAX_BURN: f32 = ${f((BURN_LAYER_COUNT - 2) / (BURN_LAYER_COUNT - 1))};

const USE_SUBGROUPS: bool = ${opts.useSubgroups};
const DITHER_ALPHA: bool = ${opts.ditherAlpha};
`
}
