/**
 * The advected smoke field — WP 4.1.
 *
 * Owns two `rgba16float` 3D textures and ping-pongs them through one combined
 * advect-plus-inject pass. `emission.ts` next door owns the physics and is the oracle; this
 * file is plumbing, and is kept out of any barrel because it imports WGSL and touches
 * `GPUDevice`.
 *
 * Grid from spec §6.1: 256 × 256 × 64 at 4 m horizontal, 2 m vertical, height above ground.
 * 8 MiB per copy, 16 MiB ping-ponged — an eighth of what the 2 m lattice would have cost, and
 * §6.1's stated reason is that the froxel raymarcher reconstructs sub-4 m structure with curl
 * noise better than a 2 m advected field reconstructs it after numerical diffusion.
 */

import type { Seconds } from '@contracts/units'
import { MAX_SIM_SUBSTEP_S, SURFACE_CELLS, SURFACE_CELL_M } from '@contracts/sim'
import { FUEL_SIZE_CLASSES } from '@contracts/sim'
import type { CellBurnoutModel } from '@sim/burnout/consumption.ts'
import CONVECTION_WGSL from '../../../shaders/sim/canopy/convection/convection.wgsl?raw'
import SMOKE_WGSL from '../../../shaders/sim/smoke/smoke.wgsl?raw'
import {
  CONVECTIVE_FRACTION,
  F_FLAMING,
  F_SMOULDERING,
  HEAT_OF_COMBUSTION,
  SOOT_YIELD_FLAMING,
  SOOT_YIELD_SMOULDERING,
} from './emission.ts'

/** Horizontal cells per axis. */
export const SMOKE_NXZ = 256
/** Vertical levels. */
export const SMOKE_NY = 64
export const SMOKE_CELL_XZ = 4
export const SMOKE_CELL_Y = 2
/** Vertical extent, m above ground. */
export const SMOKE_TOP_M = SMOKE_NY * SMOKE_CELL_Y

/**
 * Mass removed per second by entrainment dilution and deposition.
 *
 * ponytail: one scalar standing in for two different physical processes with different height
 * dependences. It is what stops a long-running fire filling the domain with a haze that never
 * clears, and 1/60 s⁻¹ gives a parcel a ~1 minute visible life, which matches the ~1.7 min a
 * 1 km domain takes to cross at 10 m/s. Replace with height-dependent entrainment when M5's
 * wind field lands.
 */
export const SMOKE_DECAY_PER_S = 1 / 60

/** `struct SmokeParams`, padded to a 16-byte multiple. */
const PARAMS_BYTES = 128

const f = (v: number): string => (Number.isInteger(v) ? `${v}.0` : `${v}`)
const u = (v: number): string => `${Math.trunc(v)}u`

export function smokePrelude(): string {
  return `// GENERATED by src/sim/smoke/field.ts — the grid is spec §6.1's, not this file's
const SMOKE_NXZ: u32 = ${u(SMOKE_NXZ)};
const SMOKE_NY: u32 = ${u(SMOKE_NY)};
const SMOKE_NXZ_F: f32 = ${f(SMOKE_NXZ)};
const SMOKE_NY_F: f32 = ${f(SMOKE_NY)};
const SMOKE_CELL_XZ: f32 = ${f(SMOKE_CELL_XZ)};
const SMOKE_CELL_Y: f32 = ${f(SMOKE_CELL_Y)};
`
}

/** Prelude + WP 3.4's plume functions + the pass. The plume supplies the buoyant velocity. */
export function buildSmokeShader(): string {
  return `${smokePrelude()}\n${CONVECTION_WGSL}\n${SMOKE_WGSL}`
}

export interface SmokeFieldInputs {
  /** WP 2.3's r32float arrival time, which ages each cell's burnout curve. */
  readonly arrivalTexture: GPUTexture
  /** WP 2.4's r8uint lifecycle state. */
  readonly stateTexture: GPUTexture
  /** WP 3.4's packed plume uniforms — the buoyant vertical velocity. */
  readonly plume: GPUBuffer
}

export interface SmokeFieldOptions {
  readonly ambientK?: number
  readonly decayPerS?: number
}

export class SmokeField {
  /** The field the renderer samples. Swaps every step; read it fresh, never cache it. */
  get current(): GPUTexture {
    return this.textures[this.cursor] as GPUTexture
  }

  private readonly device: GPUDevice
  private readonly textures: readonly [GPUTexture, GPUTexture]
  private readonly params: GPUBuffer
  private readonly sampler: GPUSampler
  private readonly advect: GPUComputePipeline
  private readonly clear: GPUComputePipeline
  /** One group per ping-pong direction; index by the CURRENT source. */
  private readonly advectGroups: GPUBindGroup[] = []
  private readonly clearGroups: GPUBindGroup[] = []
  private surfaceGroup: GPUBindGroup | null = null
  private plumeGroup: GPUBindGroup | null = null
  private cursor = 0
  private readonly ambientK: number
  private readonly decayPerS: number
  private model: CellBurnoutModel | null = null
  private windX = 0
  private windZ = 0

  constructor(device: GPUDevice, inputs: SmokeFieldInputs, options: SmokeFieldOptions = {}) {
    this.device = device
    this.ambientK = options.ambientK ?? 293.15
    this.decayPerS = options.decayPerS ?? SMOKE_DECAY_PER_S

    const make = (label: string): GPUTexture =>
      device.createTexture({
        label,
        dimension: '3d',
        size: { width: SMOKE_NXZ, height: SMOKE_NXZ, depthOrArrayLayers: SMOKE_NY },
        format: 'rgba16float',
        usage:
          GPUTextureUsage.STORAGE_BINDING |
          GPUTextureUsage.TEXTURE_BINDING |
          // COPY_SRC so `?debug` can read the field back. Omitting it is a validation error at
          // the copy, which discards the whole command buffer rather than failing locally.
          GPUTextureUsage.COPY_SRC,
      })
    this.textures = [make('smoke.fieldA'), make('smoke.fieldB')]

    this.params = device.createBuffer({
      label: 'smoke.params',
      size: PARAMS_BYTES,
      usage: GPUBufferUsage.UNIFORM | GPUBufferUsage.COPY_DST,
    })
    this.sampler = device.createSampler({
      label: 'smoke.sampler',
      magFilter: 'linear',
      minFilter: 'linear',
      addressModeU: 'clamp-to-edge',
      addressModeV: 'clamp-to-edge',
      addressModeW: 'clamp-to-edge',
    })

    const module = device.createShaderModule({ label: 'smoke', code: buildSmokeShader() })
    const pipeline = (entryPoint: string): GPUComputePipeline =>
      device.createComputePipeline({
        label: `smoke.${entryPoint}`,
        layout: 'auto',
        compute: { module, entryPoint },
      })
    this.advect = pipeline('advect')
    this.clear = pipeline('clearField')

    for (let i = 0; i < 2; i++) {
      const src = this.textures[i] as GPUTexture
      const dst = this.textures[1 - i] as GPUTexture
      this.advectGroups.push(
        device.createBindGroup({
          label: `smoke.advect.g0[${i}]`,
          layout: this.advect.getBindGroupLayout(0),
          entries: [
            { binding: 0, resource: { buffer: this.params } },
            { binding: 1, resource: src.createView() },
            { binding: 2, resource: dst.createView() },
            { binding: 3, resource: this.sampler },
          ],
        }),
      )
      // `clearField` writes only, so its implicit layout has just the storage binding — and an
      // implicit layout is compatible only with the pipeline that created it, so this cannot
      // share the group above.
      this.clearGroups.push(
        device.createBindGroup({
          label: `smoke.clear.g0[${i}]`,
          layout: this.clear.getBindGroupLayout(0),
          entries: [{ binding: 2, resource: (this.textures[i] as GPUTexture).createView() }],
        }),
      )
    }

    this.bindSurface(inputs)
  }

  /** The burnout curve of the domain's fuel. Same object WP 2.4 uses; see `FireSim`. */
  setModel(model: CellBurnoutModel): void {
    this.model = model
  }

  /** Horizontal wind, m/s in world x and z. */
  setWind(x: number, z: number): void {
    this.windX = x
    this.windZ = z
  }

  /** Zero both buffers. Encoded, so it costs a submit like anything else. */
  reset(encoder: GPUCommandEncoder): void {
    for (let i = 0; i < 2; i++) {
      const pass = encoder.beginComputePass({ label: `smoke.clear[${i}]` })
      pass.setPipeline(this.clear)
      pass.setBindGroup(0, this.clearGroups[i] as GPUBindGroup)
      pass.dispatchWorkgroups(SMOKE_NXZ / 4, SMOKE_NXZ / 4, SMOKE_NY / 4)
      pass.end()
    }
    this.cursor = 0
  }

  /**
   * Advance the field by `dt`, injecting from the burning surface as it goes.
   *
   * One pass. Injection is folded into the advection invocation rather than run separately,
   * because a separate injection would have to read and write the same texture — see the
   * shader's own header.
   */
  step(encoder: GPUCommandEncoder, dt: Seconds, nowS: number): void {
    if (this.model === null || this.surfaceGroup === null || !(dt > 0)) return
    // Substepped for the reason on MAX_SIM_SUBSTEP_S. Semi-Lagrangian advection is stable at
    // any step, but it is not ACCURATE at any step: one 0.5 s step moves a parcel half a cell
    // and smears it over the trilinear stencil, so a fast clock diffused the plume away faster
    // than it rose. The injection term is inside the loop with everything else, so a substepped
    // interval injects the same total mass as a single step of the same length.
    const subs = Math.max(1, Math.ceil((dt as number) / MAX_SIM_SUBSTEP_S))
    const subDt = (dt as number) / subs
    for (let i = 0; i < subs; i++) {
      this.writeParams(subDt as Seconds, nowS - (dt as number) + subDt * (i + 1))
      const pass = encoder.beginComputePass({ label: 'smoke.advect' })
      pass.setPipeline(this.advect)
      pass.setBindGroup(0, this.advectGroups[this.cursor] as GPUBindGroup)
      pass.setBindGroup(1, this.surfaceGroup)
      pass.setBindGroup(3, this.plumeGroup as GPUBindGroup)
      pass.dispatchWorkgroups(SMOKE_NXZ / 4, SMOKE_NXZ / 4, SMOKE_NY / 4)
      pass.end()
      this.cursor = 1 - this.cursor
    }
  }

  destroy(): void {
    for (const t of this.textures) t.destroy()
    this.params.destroy()
  }

  private bindSurface(inputs: SmokeFieldInputs): void {
    this.surfaceGroup = this.device.createBindGroup({
      label: 'smoke.surface.g1',
      layout: this.advect.getBindGroupLayout(1),
      entries: [
        { binding: 0, resource: inputs.arrivalTexture.createView() },
        { binding: 1, resource: inputs.stateTexture.createView() },
      ],
    })
    // The plume uniform lives in convection.wgsl's own `@group(3)`, hard-coded there. The
    // smoke pass declares groups 0 and 1, so group 2 is simply empty and group 3 is the
    // plume's — ask the pipeline for the layout rather than assuming a renumbering.
    this.plumeGroup = this.device.createBindGroup({
      label: 'smoke.plume',
      layout: this.advect.getBindGroupLayout(3),
      entries: [{ binding: 0, resource: { buffer: inputs.plume } }],
    })
  }

  private writeParams(dt: Seconds, nowS: number): void {
    const m = this.model as CellBurnoutModel
    const buf = new ArrayBuffer(PARAMS_BYTES)
    const v = new DataView(buf)
    v.setFloat32(0, dt, true)
    v.setFloat32(4, nowS, true)
    v.setFloat32(8, this.ambientK, true)
    v.setUint32(12, SURFACE_CELLS, true)

    v.setFloat32(16, SURFACE_CELL_M, true)
    v.setFloat32(20, this.windX, true)
    v.setFloat32(24, this.windZ, true)
    v.setFloat32(28, this.decayPerS, true)

    // invTau[0..3], loadFrac[0..3], then class 4 on its own: a vec4 pair plus scalars keeps the
    // std140 alignment obvious rather than relying on an array-of-5 stride rule.
    FUEL_SIZE_CLASSES.forEach((c, i) => {
      const load = m.load[c]
      if (i < 4) {
        v.setFloat32(32 + i * 4, load > 0 ? 1 / m.tau[c] : 0, true)
        v.setFloat32(48 + i * 4, load > 0 ? m.loadFraction[c] : 0, true)
      }
    })
    const last = FUEL_SIZE_CLASSES[4] as (typeof FUEL_SIZE_CLASSES)[number]
    v.setFloat32(64, m.load[last] > 0 ? 1 / m.tau[last] : 0, true)
    v.setFloat32(68, m.load[last] > 0 ? m.loadFraction[last] : 0, true)
    v.setFloat32(72, m.totalLoad, true)
    v.setFloat32(76, m.residenceTime, true)

    v.setFloat32(80, SOOT_YIELD_FLAMING, true)
    v.setFloat32(84, SOOT_YIELD_SMOULDERING, true)
    v.setFloat32(88, F_FLAMING, true)
    v.setFloat32(92, F_SMOULDERING, true)

    v.setFloat32(96, HEAT_OF_COMBUSTION, true)
    v.setFloat32(100, CONVECTIVE_FRACTION, true)
    this.device.queue.writeBuffer(this.params, 0, buf)
  }
}
