/**
 * WGSL assembly for the fire debug overlay — WP 2.6.
 *
 * The colour tables exist once, in `views.ts`. This generates the WGSL constants from them
 * and prepends them to the shader, the same trick WP 1.5 uses for its layout constants:
 * duplicated constants are the one bug a shader cannot be unit-tested out of, because the
 * CPU oracle and the GPU are then two different programs.
 *
 * Ramps are resampled to a fixed number of evenly-spaced entries so the shader lookup is a
 * single mix with no search — the stop positions are a CPU concern.
 */

import firedebugWgsl from '../../../shaders/firedebug/firedebug.wgsl?raw'
import { CELL_BURNING, CELL_BURNT, CELL_UNBURNT, type CellState } from '@contracts/sim.ts'
import { RAMPS, STATE_COLORS, rampColor, type Ramp } from './views.ts'

/**
 * Entries per resampled ramp. Even spacing rounds the authored ramp's kinks; 32 keeps the
 * worst-case per-channel error under 0.02, which is where the shader stops disagreeing
 * visibly with the CSS gradient in the legend (which uses the exact stops).
 */
export const RAMP_SAMPLES = 32

/** WGSL has no implicit int->float, so every literal must carry a decimal point. */
const f = (v: number): string => v.toFixed(4)

/** Evenly-spaced resample of a ramp, so the shader can index it directly. */
export function resampleRamp(ramp: Ramp, n = RAMP_SAMPLES): [number, number, number][] {
  const out: [number, number, number][] = []
  for (let i = 0; i < n; i++) out.push(rampColor(ramp, n > 1 ? i / (n - 1) : 0))
  return out
}

function rampDecl(name: string, ramp: Ramp): string {
  const entries = resampleRamp(ramp)
    .map((c) => `vec3<f32>(${f(c[0])}, ${f(c[1])}, ${f(c[2])})`)
    .join(', ')
  return `var<private> ${name} : array<vec3<f32>, ${RAMP_SAMPLES}> = array<vec3<f32>, ${RAMP_SAMPLES}>(${entries});`
}

/** The generated half of the shader. Exported so the test can assert it against the tables. */
export function fireDebugPrelude(): string {
  const order: readonly CellState[] = [CELL_UNBURNT, CELL_BURNING, CELL_BURNT]
  const state = order
    .map((s) => {
      const c = STATE_COLORS[s]
      return `vec4<f32>(${f(c[0])}, ${f(c[1])}, ${f(c[2])}, ${f(c[3])})`
    })
    .join(', ')
  return [
    '// GENERATED by src/render/firedebug/shaders.ts from views.ts. Do not edit here.',
    `const FD_RAMP_N : u32 = ${RAMP_SAMPLES}u;`,
    rampDecl('FD_RAMP_INTENSITY', RAMPS.intensity),
    rampDecl('FD_RAMP_ARRIVAL', RAMPS.arrival),
    rampDecl('FD_RAMP_CONSUMED', RAMPS.consumed),
    `var<private> FD_STATE_COLORS : array<vec4<f32>, 3> = array<vec4<f32>, 3>(${state});`,
  ].join('\n')
}

export const FIRE_DEBUG_VS = 'vs_firedebug'
export const FIRE_DEBUG_FS = 'fs_firedebug'

export function fireDebugShader(): string {
  return `${fireDebugPrelude()}\n\n${firedebugWgsl}`
}
