/**
 * WGSL prelude for the canopy store. Every constant the shader and the TypeScript both rely
 * on is emitted from the TypeScript definition, so there is no second copy to drift — the same
 * rule `src/sim/surface/shaders.ts` follows.
 *
 * Consumers call `canopyStorageWgsl(group)` and prepend the result to their own shader. The
 * bind group index is a parameter because each canopy pass owns its own group numbering; the
 * *binding* numbers within the group are fixed and documented on `CanopyVoxelStore`.
 *
 * No `enable f16`. §7.2 requires it: f16 pairs live inside `u32` and are moved with core-WGSL
 * `pack2x16float`/`unpack2x16float`, so the build runs on adapters that expose `shader-f16`
 * inconsistently. That costs ~2 ALU ops per access and buys portability.
 */

import { CANOPY_GRID, INVALID_VOXEL, Z_MASK, ZCOUNT_SHIFT } from './layout.ts'
import { SAV_MAX_PER_M, SAV_MIN_PER_M } from './store.ts'

import ADDRESS_WGSL from '../../../../shaders/sim/canopy/storage/address.wgsl?raw'

/** G for a spherical leaf-angle distribution (Nilson 1971; spec §30 §7.3). */
export const G_SPHERICAL = 0.5

const u = (v: number): string => `${Math.trunc(v)}u`
const f = (v: number): string => (Number.isInteger(v) ? `${v}.0` : `${v}`)

export function canopyStoragePrelude(group: number): string {
  const g = CANOPY_GRID
  return `// generated by src/sim/canopy/storage/shaders.ts — do not edit
const CANOPY_INVALID: u32 = ${u(INVALID_VOXEL)};
const CANOPY_NXY: u32 = ${u(g.nxy)};
const CANOPY_NZ: u32 = ${u(g.nz)};
const CANOPY_CELL: f32 = ${f(g.cellM)};
const CANOPY_INV_CELL: f32 = ${f(1 / g.cellM)};
const CANOPY_Z_MASK: u32 = ${u(Z_MASK)};
const CANOPY_ZCOUNT_SHIFT: u32 = ${u(ZCOUNT_SHIFT)};
const CANOPY_SAV_MIN: f32 = ${f(SAV_MIN_PER_M)};
const CANOPY_SAV_DECODE: f32 = ${Math.log(SAV_MAX_PER_M / SAV_MIN_PER_M) / 255};
const CANOPY_G_SPHERICAL: f32 = ${f(G_SPHERICAL)};

struct CanopyColumn { header: u32, offset: u32 }

@group(${Math.trunc(group)}) @binding(0) var<storage, read> canopyColumns: array<CanopyColumn>;
@group(${Math.trunc(group)}) @binding(1) var<storage, read> canopyGround: array<f32>;
@group(${Math.trunc(group)}) @binding(2) var<storage, read_write> canopyPoolA: array<vec4<u32>>;
@group(${Math.trunc(group)}) @binding(3) var<storage, read> canopyPoolB: array<vec2<u32>>;
@group(${Math.trunc(group)}) @binding(4) var<storage, read_write> canopyPoolC: array<f32>;
`
}

/** Prelude + addressing/accessor functions, ready to concatenate ahead of a pass. */
export function canopyStorageWgsl(group: number): string {
  return `${canopyStoragePrelude(group)}\n${ADDRESS_WGSL}`
}
