#!/usr/bin/env node
/**
 * Scans docs/spec for callout markers and emits docs/spec/_open-questions.md.
 *
 * The specification carries its own uncertainty inline, which is the right place for it —
 * an implementer reading §7.5 needs to know §7.5 is unverified. But scattered across eight
 * files it is impossible to see what is left. This regenerates a single dashboard from the
 * documents themselves, so it can never drift out of date the way a hand-maintained list
 * would.
 *
 *   node scripts/spec-status.mjs
 */

import { readdir, readFile, writeFile } from 'node:fs/promises'
import { join, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

const SPEC_DIR = join(dirname(fileURLToPath(import.meta.url)), '..', 'docs', 'spec')

/** Marker → how it is reported. Order matters: longest/most specific first. */
const MARKERS = [
  { re: /\*\*OPEN QUESTION \(unverified\):\*\*/, kind: 'open', icon: '🔴' },
  { re: /\*\*NUMERICAL TRAP\.?\*\*/, kind: 'trap', icon: '⚠️' },
  { re: /\*\*CLOSED[^*]*\*\*/, kind: 'closed', icon: '🟢' },
  { re: /\*\*NORMATIVE[^*]*\*\*/, kind: 'normative', icon: '🔵' },
  { re: /\*\*STATUS: `?estimated`?\.?\*\*/, kind: 'estimated', icon: '🟡' },
]

const LABEL = {
  open: 'Open — unverified',
  closed: 'Closed',
  normative: 'Normative decision',
  estimated: 'Shipping as `estimated`',
  trap: 'Known trap',
}

/** Nearest preceding markdown heading, so each item says where it lives. */
function sectionFor(lines, idx) {
  for (let i = idx; i >= 0; i--) {
    const l = lines[i] ?? ''
    if (/^#{2,4}\s/.test(l)) return l.replace(/^#+\s*/, '').trim()
  }
  return '(top of document)'
}

/** First sentence of the callout body, trimmed for the table. */
function gist(text) {
  const body = text
    .replace(/^>\s*/gm, '')
    .replace(/\*\*[A-Z][^*]*\*\*/, '')
    .replace(/[`*_$]/g, '')
    .replace(/\s+/g, ' ')
    .trim()
  const cut = body.slice(0, 190)
  return cut.length < body.length ? `${cut}…` : cut
}

const files = (await readdir(SPEC_DIR)).filter((f) => f.endsWith('.md') && !f.startsWith('_')).sort()

const items = []
for (const file of files) {
  const text = await readFile(join(SPEC_DIR, file), 'utf8')
  const lines = text.split('\n')
  lines.forEach((line, i) => {
    for (const m of MARKERS) {
      if (m.re.test(line)) {
        // Callouts are blockquotes; gather the contiguous quoted block.
        let block = line
        for (let j = i + 1; j < lines.length && (lines[j] ?? '').startsWith('>'); j++) block += ` ${lines[j]}`
        items.push({ file, line: i + 1, kind: m.kind, icon: m.icon, section: sectionFor(lines, i), gist: gist(block) })
        return
      }
    }
  })
}

const counts = items.reduce((a, it) => ({ ...a, [it.kind]: (a[it.kind] ?? 0) + 1 }), {})
const order = ['open', 'estimated', 'trap', 'normative', 'closed']

let out = `# Specification Status

*Generated by \`scripts/spec-status.mjs\`. Do not edit by hand — rerun the script.*

Every entry is a callout embedded in a spec document. Regenerating from the documents
themselves means this dashboard cannot drift out of date.

| | Count |
|---|---|
${order.map((k) => `| ${MARKERS.find((m) => m.kind === k)?.icon} ${LABEL[k]} | ${counts[k] ?? 0} |`).join('\n')}
| **Total** | **${items.length}** |

**🔴 Open items block code that depends on them.** Per spec §0.7.5, a work package must
either close the question first or explicitly downgrade the affected model's validation
status. 🟡 items are shipping with acknowledged estimates and are surfaced in the HUD.
`

for (const kind of order) {
  const group = items.filter((it) => it.kind === kind)
  if (group.length === 0) continue
  const icon = MARKERS.find((m) => m.kind === kind)?.icon
  out += `\n## ${icon} ${LABEL[kind]} (${group.length})\n\n| Document | Section | Detail |\n|---|---|---|\n`
  for (const it of group) {
    out += `| [\`${it.file}:${it.line}\`](${it.file}#L${it.line}) | ${it.section} | ${it.gist} |\n`
  }
}

await writeFile(join(SPEC_DIR, '_open-questions.md'), out, 'utf8')

console.log(`Scanned ${files.length} spec documents, found ${items.length} callouts:`)
for (const k of order) if (counts[k]) console.log(`  ${MARKERS.find((m) => m.kind === k)?.icon} ${String(counts[k]).padStart(3)}  ${LABEL[k]}`)
console.log(`\nWrote docs/spec/_open-questions.md`)
