/**
 * WGSL assembly for the radiation passes.
 *
 * Same rule as the surface package: every number the two languages must agree on is emitted
 * here from the TypeScript definition, so there is no second copy to drift. If a fixed-point
 * scale moves, the shader moves with it or `shaders.test.ts` fails.
 *
 * The fixed-point scales are the ones that matter. A drifted `POWER_FIXED_SCALE` would not
 * produce a compile error or a black screen — it would produce a fire that radiates a
 * plausible-looking wrong amount, which is the exact failure mode §0.6 was written about.
 */

import {
  A2_MIN,
  CLUSTER_WORKGROUP,
  EMIT_CELL_M,
  EMIT_CLUSTER_CAP,
  EMIT_GRID_CELLS,
  EMIT_NI,
  EMIT_NJ,
  EMIT_NK,
  EMIT_SLOTS,
  GATHER_WORKGROUP,
  MIN_RAY_COUNT,
  OVERFLOW_A2,
  OVERFLOW_CENTRE_X,
  OVERFLOW_CENTRE_Y,
  OVERFLOW_CENTRE_Z,
  OVERFLOW_POWER_SHIFT,
  POSITION_BIAS_M,
  POSITION_FIXED_SCALE,
  POWER_FIXED_SCALE,
  RAD_CELLS_PER_BRICK_AXIS,
  RAD_CELL_M,
  RAD_NI,
  RAD_NJ,
  RAD_NK,
  RAY_COUNTS,
  RAY_TAPS,
} from './layout.ts'
import { LEAF_PROJECTION_SPHERICAL } from './optics.ts'

import CLUSTERS_WGSL from '../../../../shaders/sim/canopy/radiation/clusters.wgsl?raw'
import EXTINCTION_WGSL from '../../../../shaders/sim/canopy/radiation/extinction.wgsl?raw'
import GATHER_WGSL from '../../../../shaders/sim/canopy/radiation/gather.wgsl?raw'
import EMIT_SURFACE_WGSL from '../../../../shaders/sim/canopy/radiation/emit_surface.wgsl?raw'

/** Brick indirection grid, §7.2: 512/8 x 512/8 x 64/8, with k vertical. */
export const BRICK_NI = 64
export const BRICK_NJ = 64
export const BRICK_NK = 8

/** Largest ray count any quality tier asks for; sizes the shader's register arrays. */
export const MAX_RAY_COUNT = Math.max(...RAY_COUNTS)

export interface RadiationShaderOptions {
  /** World position of grid index (0,0,0)'s minimum corner. */
  readonly originX: number
  readonly originY: number
  readonly originZ: number
}

export const DEFAULT_SHADER_OPTIONS: RadiationShaderOptions = { originX: 0, originY: 0, originZ: 0 }

const u = (v: number): string => `${Math.trunc(v)}u`
const f = (v: number): string => (Number.isInteger(v) ? `${v}.0` : `${v}`)

export function radiationPrelude(opts: RadiationShaderOptions = DEFAULT_SHADER_OPTIONS): string {
  return `// GENERATED by src/sim/canopy/radiation/shaders.ts — do not edit these in the .wgsl files.
const RAD_CELL_M: f32 = ${f(RAD_CELL_M)};
const RAD_NI: u32 = ${u(RAD_NI)};
const RAD_NJ: u32 = ${u(RAD_NJ)};
const RAD_NK: u32 = ${u(RAD_NK)};
const RAD_NI_F: f32 = ${f(RAD_NI)};
const RAD_NJ_F: f32 = ${f(RAD_NJ)};
const RAD_NK_F: f32 = ${f(RAD_NK)};
const RAD_ORIGIN_X: f32 = ${f(opts.originX)};
const RAD_ORIGIN_Y: f32 = ${f(opts.originY)};
const RAD_ORIGIN_Z: f32 = ${f(opts.originZ)};

const RAD_CELLS_PER_BRICK: u32 = ${u(RAD_CELLS_PER_BRICK_AXIS)};
const BRICK_NI: u32 = ${u(BRICK_NI)};
const BRICK_NJ: u32 = ${u(BRICK_NJ)};
const BRICK_NK: u32 = ${u(BRICK_NK)};
const GATHER_WG: u32 = ${u(GATHER_WORKGROUP)};

const EMIT_CELL_M: f32 = ${f(EMIT_CELL_M)};
const EMIT_NI: u32 = ${u(EMIT_NI)};
const EMIT_NJ: u32 = ${u(EMIT_NJ)};
const EMIT_NK: u32 = ${u(EMIT_NK)};
const EMIT_NI_F: f32 = ${f(EMIT_NI)};
const EMIT_NJ_F: f32 = ${f(EMIT_NJ)};
const EMIT_NK_F: f32 = ${f(EMIT_NK)};
const EMIT_ORIGIN_X: f32 = ${f(opts.originX)};
const EMIT_ORIGIN_Y: f32 = ${f(opts.originY)};
const EMIT_ORIGIN_Z: f32 = ${f(opts.originZ)};
const EMIT_GRID_CELLS: u32 = ${u(EMIT_GRID_CELLS)};
const EMIT_SLOTS: u32 = ${u(EMIT_SLOTS)};
const EMIT_CLUSTER_CAP: u32 = ${u(EMIT_CLUSTER_CAP)};
const CLUSTER_WG: u32 = ${u(CLUSTER_WORKGROUP)};

// Fixed point. These four are the ones a silent drift would corrupt invisibly.
const POWER_FIXED_SCALE: f32 = ${f(POWER_FIXED_SCALE)};
const POSITION_BIAS_M: f32 = ${f(POSITION_BIAS_M)};
const POSITION_FIXED_SCALE: f32 = ${f(POSITION_FIXED_SCALE)};
const A2_MIN: f32 = ${f(A2_MIN)};

const OVERFLOW_POWER_SHIFT: u32 = ${u(OVERFLOW_POWER_SHIFT)};
const OVERFLOW_CENTRE: vec3f = vec3f(${f(OVERFLOW_CENTRE_X)}, ${f(OVERFLOW_CENTRE_Y)}, ${f(OVERFLOW_CENTRE_Z)});
const OVERFLOW_A2: f32 = ${f(OVERFLOW_A2)};

const MIN_RAY_COUNT: u32 = ${u(MIN_RAY_COUNT)};
const MAX_RAY_COUNT: u32 = ${u(MAX_RAY_COUNT)};
const RAY_TAPS: u32 = ${u(RAY_TAPS)};
const RAY_TAPS_F: f32 = ${f(RAY_TAPS)};

const LEAF_PROJECTION: f32 = ${f(LEAF_PROJECTION_SPHERICAL)};
const FOUR_PI: f32 = ${4 * Math.PI};
const W_TO_KW: f32 = 0.001;
`
}

export interface RadiationShaders {
  readonly extinction: string
  readonly clusters: string
  readonly gather: string
  /** Surface fire state -> the emitter list `clusters` scatters. See `surfaceEmitters.ts`. */
  readonly emitSurface: string
}

export function buildRadiationShaders(
  opts: RadiationShaderOptions = DEFAULT_SHADER_OPTIONS,
): RadiationShaders {
  const p = radiationPrelude(opts)
  return {
    extinction: `${p}\n${EXTINCTION_WGSL}`,
    clusters: `${p}\n${CLUSTERS_WGSL}`,
    gather: `${p}\n${GATHER_WGSL}`,
    emitSurface: `${p}\n${EMIT_SURFACE_WGSL}`,
  }
}
