/**
 * WGSL assembly for the surface solver.
 *
 * Every number both languages have to agree on is emitted here from the TypeScript
 * definition, so there is no second copy to drift: the byte slots come out of `FIELDS`, the
 * LUT stride out of `coefficients.ts`, the moisture scales out of `layout.ts`. If a field
 * moves, the shader moves with it or the build breaks.
 *
 * ## Where `shader-f16` is used, and where it deliberately is not
 *
 * **Storage: yes.** The two caches are 16-bit float textures — `rgba16float` for the ellipse
 * cache and `rg16float` for the ROS base. Those need no `enable f16` (the format converts on
 * load/store) and they halve the pass's traffic, which §4.3's own callout identifies as the
 * binding constraint.
 *
 * **Arithmetic: no, and that is not laziness.** `φ_w = C·U^B` overflows f16 in the
 * intermediate: at the design-ceiling wind of ~3000 ft min⁻¹ with σ = 2200 ft⁻¹ (GR1), B is
 * ≈ 1.53 and `U^B` ≈ 3×10⁵ against an f16 maximum of 65504. Even in the §4.2 GR2 case `U^B`
 * is 7×10³, so the headroom is one gust. Separately, `B` itself in f16 carries a half-ulp of
 * 4.9×10⁻⁴, which through `U^B` is a 0.3% error in `φ_w` — larger than the tolerance this
 * package is accepted at. The kernel is f32 throughout, and `B` is never stored in a 16-bit
 * texture for the same reason (the substep re-reads it from the f32 LUT rather than caching
 * it alongside `R₀`).
 */

import {
  DEAD_MOISTURE_FULL_SCALE,
  FIELDS,
  FLAG_BURNABLE,
  FLAG_BURNT_OUT,
  FLAG_IGNITED,
  FLAG_IGNITION_REQUEST,
  LIVE_MOISTURE_FULL_SCALE,
  MASS_FULL_SCALE,
  PLANE_COUNT,
  SURFACE_CELLS,
  SURFACE_CELL_COUNT,
  SURFACE_CELL_M,
} from './layout.ts'
import { COEFF_VEC4S, CURE_BINS } from './coefficients.ts'
import { MAX_SLOPE_TANGENT } from './rothermel.ts'
import type { WindLimitMode } from './rothermel.ts'

import COMMON_WGSL from '../../../shaders/sim/surface/common.wgsl?raw'
import ROS_BASE_WGSL from '../../../shaders/sim/surface/ros_base.wgsl?raw'
import ROS_SUBSTEP_WGSL from '../../../shaders/sim/surface/ros_substep.wgsl?raw'

/** 8×8. 2048/8 = 256 workgroups per axis, far under `maxComputeWorkgroupsPerDimension`. */
export const SURFACE_WORKGROUP = 8

const u = (v: number): string => `${Math.trunc(v)}u`
const f = (v: number): string => (Number.isInteger(v) ? `${v}.0` : `${v}`)

export const WIND_LIMIT_CODE: Record<WindLimitMode, number> = { none: 0, sanity: 1, behave: 2 }

export interface SurfaceShaderOptions {
  /** §4.5. Default `sanity`: no hard cap, inert rail only. `behave` is the debug toggle. */
  readonly windLimit: WindLimitMode
}

export function surfacePrelude(opts: SurfaceShaderOptions): string {
  const field = (name: keyof typeof FIELDS): string => {
    const s = FIELDS[name]
    const upper = name.replace(/([A-Z0-9]+)/g, '_$1').toUpperCase()
    return `const F_${upper}_PLANE: u32 = ${u(s.plane)};\nconst F_${upper}_BYTE: u32 = ${u(s.byte)};`
  }
  return `// GENERATED by src/sim/surface/shaders.ts — do not edit these in the .wgsl files.
const SURFACE_CELLS: u32 = ${u(SURFACE_CELLS)};
const SURFACE_CELL_M: f32 = ${f(SURFACE_CELL_M)};
const SURFACE_CELL_COUNT: u32 = ${u(SURFACE_CELL_COUNT)};
const PLANE_STRIDE: u32 = ${u(SURFACE_CELL_COUNT)};
const PLANE_COUNT: u32 = ${u(PLANE_COUNT)};
const WG: u32 = ${u(SURFACE_WORKGROUP)};

const CURE_BINS: u32 = ${u(CURE_BINS)};
const CURE_BINS_F: f32 = ${f(CURE_BINS)};
const COEFF_VEC4S: u32 = ${u(COEFF_VEC4S)};

const DEAD_MOISTURE_FULL_SCALE: f32 = ${f(DEAD_MOISTURE_FULL_SCALE)};
const LIVE_MOISTURE_FULL_SCALE: f32 = ${f(LIVE_MOISTURE_FULL_SCALE)};
const MASS_FULL_SCALE: f32 = ${f(MASS_FULL_SCALE)};
const MAX_SLOPE_TANGENT: f32 = ${f(MAX_SLOPE_TANGENT)};

const FLAG_BURNABLE: u32 = ${u(FLAG_BURNABLE)};
const FLAG_IGNITED: u32 = ${u(FLAG_IGNITED)};
const FLAG_BURNT_OUT: u32 = ${u(FLAG_BURNT_OUT)};
const FLAG_IGNITION_REQUEST: u32 = ${u(FLAG_IGNITION_REQUEST)};

${(Object.keys(FIELDS) as (keyof typeof FIELDS)[]).map(field).join('\n')}

// Unit boundary. Rothermel's coefficients are BTU-lb-ft-min fits and are NOT converted;
// the kernel converts its inputs in and its outputs out, exactly as the CPU path does.
const FTMIN_TO_MPS: f32 = ${f(0.3048 / 60)};
const MPS_TO_FTMIN: f32 = ${f(60 / 0.3048)};
const BTUFT2MIN_TO_KWM2: f32 = ${f(1055.05585262 / 0.3048 ** 2 / 60 / 1000)};
const FTMIN_PER_MPH: f32 = 88.0;

// §4.5 wind limit: 0 = none, 1 = inert sanity rail (default), 2 = legacy 0.9*I_R BEHAVE cap.
const WIND_LIMIT_MODE: u32 = ${u(WIND_LIMIT_CODE[opts.windLimit])};
`
}

export interface SurfaceShaderSources {
  readonly rosBase: string
  readonly rosSubstep: string
}

export function buildSurfaceShaders(opts: SurfaceShaderOptions): SurfaceShaderSources {
  const head = `${surfacePrelude(opts)}\n${COMMON_WGSL}\n`
  return {
    rosBase: head + ROS_BASE_WGSL,
    rosSubstep: head + ROS_SUBSTEP_WGSL,
  }
}
